### ISSUE TITLE
feature request: Use local file for overwriting FUNDING.yml files on remote branches

### ISSUE THREAD

**Issue by munierujp** [azu/github-funding-yml-updater#1]
I'd like to add external funding platforms to my FUNDING.yml files.

## Idea of usage
Create `FUNDING.yml` to local.

```yaml
github: [octocat, surftocat]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
```

Run command.

```sh
$ github-funding-yml-updater --mode overwrite --user octocat --list-file list.txt --funding-file FUNDING.yml --token ${GITHUB_TOKEN} --write
```
